server:
  port: 8088
spring:
  application:
    name: config-svc
  cloud:
    config:
      server:
        native:
          search-locations : file:///D:/OpenSourceProjects/MicroserviesOne/config-svc/src/main/resources/config
      label : main
  profiles:
    active: native